name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker-compose build
      
    - name: Test Docker image
      run: |
        docker-compose up -d
        # Add tests here if needed
        sleep 5
        curl -s http://localhost:8080 | grep "Docker + GitHub Actions Template"
        docker-compose down
      
    - name: Deploy to production
      if: github.event_name != 'pull_request'
      run: |
        docker-compose down
        docker-compose up -d 